  server:
    port : 8081

  spring :
    application:
      name: user-service
    datasource :
      url : jdbc:postgresql://localhost:5432/microservices
      username : postgres
      password : postgres
      driver-class-name : org.postgresql.Driver
    devtools :
      restart :
        enabled : false

    jpa :
      hibernate :
        ddl-auto : update
      show-sql : true


  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone : http://localhost:8761/eureka
    instance:
      prefer-ip-address: true

  ratingService :
    userRating :
      endpointURL : http://RATING-SERVICE/ratings/user/

  management:
    health:
      circuitbreakers:
        enabled: true
    endpoints:
      web:
        exposure:
          include: health


    endpoint:
      health:
        show-details: always

  resilience4j:
    circuitbreaker:
      instances:
        ratingHotelBreaker :
          registerHealthIndicator : true
          eventConsumerBufferSize : 10
          failureRateThreshold : 50
          minimumNumberOfCalls : 5
          automaticTransitionFromOpenToHalfOpenEnabled : true
          waitDurationInOpenState : 5s
          permittedNumberOfCallsInHalfOpenState : 2
          slidingWindowSize : 10
          slidingWindowType : COUNT_BASED

    retry:
      instances:
        ratingServiceRetry :
          max-attempts: 3
          wait-duration: 5s




